### ISSUE TITLE
Make selected tab text contain the accent color

### ISSUE THREAD

**Issue by schloerke** [rstudio/bootstraplib#63]
Having the _selected_ tab being less "visible" than the other tabs seems odd.  

Can this be switched?

Ex: With a dark foreground and lighter background and accent color of orange, the selected tab should have orange text and the other tabs should have grey text.  When hovering, the tab text should switch to orange.

**Comment by cpsievert** [comment]
> With a dark foreground and lighter background and accent color of orange, the selected tab should have orange text and the other tabs should have grey text

The text color of non-active tabs is intentionally based on `$link-color` (I'm pretty sure this is for accessibility reasons...tab links are essentially hyperlinks and so should be styled the same way)

**Comment by cpsievert** [comment]
FWIW, there will soon be a section on setting the bg/fg color of the active tab

**Comment by schloerke** [comment]
Hmmmmm. I understand the logic. I still think it's wrong. 

Feel free to close this issue.
