### ISSUE TITLE
Theme customizer not working

### ISSUE THREAD

**Issue by joekroese** [rstudio/bootstraplib#74]
## Summary

Theme customizer is not responding to clicks on menu items other than 'Background color' and 'Foreground color'.

## Details

'Background color' and 'Foreground color' work as expected, changing the values and printing the changed code to the console. However, clicking on any of the other items in the Theme customizer does not work. These items do not expand their view and so you cannot change the value of the parameters.

![bootstraplib-theme-customizer-error-demonstration](https://user-images.githubusercontent.com/7649772/85279982-96189700-b487-11ea-8f62-2306493cfb9d.gif)

Opening it in the browser gives the same issues.

## Reproduce

On Mac Catalina 10.15.4, R 4.0.0, RStudio 1.3.959, run: 

```
bootstraplib::bs_theme_new(bootswatch = "sketchy")
bootstraplib::bs_theme_preview()
```

Clicking on any of the options ('Accent colors', 'Fonts' etc.) will not change the view.

**Comment by cpsievert** [comment]
Woah, this is very surprising! After you change the background or foreground, could you please open your browsers developer tools (i.e.,  Right-click -> Inspect Element -> Console Tab) and report any errors that you see? Also what browsers have you tried?

**Comment by cpsievert** [comment]
Oh actually, I can reproduce, here's the error

<img width="1013" alt="Screen Shot 2020-06-23 at 11 04 45 AM" src="https://user-images.githubusercontent.com/1365941/85427485-6c23ab00-b541-11ea-8889-06a11f5c18d0.png">

**Comment by cpsievert** [comment]
I believe this issue was recently fixed, please re-open if you encounter any issues @joekroese

**Comment by joekroese** [comment]
I can confirm the fix - it works for me now :) Thanks for letting me know. I'm looking forward to using this package for my next shiny project!
